env:
- HEROKU_DOCKER_REGISTRY="dokku"
stages:
- build
- test
- deploy
jobs:
  include:
  - stage: build
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build -t $DOCKER_USER/$DOCKER_APP:$TRAVIS_COMMIT .
    - docker push $DOCKER_USER/$DOCKER_APP:$TRAVIS_COMMIT
  - stage: test
    script:
    - docker run --env-file ./docker/.env-test -w /home/docker/www $DOCKER_USER/$DOCKER_APP:$TRAVIS_COMMIT
      sh -c "composer run-script run-unit-tests"
  - stage: deploy
    script:
    - eval "$(ssh-agent -s)"
    - chmod 600 .travis/deploy.key
    - ssh-add .travis/deploy.key
    - ssh-keyscan tombennett.info >> ~/.ssh/known_hosts
    - ssh root@tombennett.info "docker pull $DOCKER_USER/$DOCKER_APP:$TRAVIS_COMMIT"
    - ssh root@tombennett.info "docker tag $DOCKER_USER/$DOCKER_APP:$TRAVIS_COMMIT $HEROKU_DOCKER_REGISTRY/$DOCKER_APP:$TRAVIS_COMMIT"
    - ssh root@tombennett.info "dokku tags:deploy $DOCKER_APP $TRAVIS_COMMIT"
    #- ssh root@tombennett.info "dokku proxy:ports-add $DOCKER_APP http:80:8001"
    #- ssh root@tombennett.info "dokku proxy:ports-remove $DOCKER_APP http:8001:8001"
before_install:
- openssl aes-256-cbc -K $encrypted_811eb66fa22a_key -iv $encrypted_811eb66fa22a_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d