variables:
  DOCKER_APP: DOCKER_APP
  DOCKER_USER: DOCKER_USER
  DOCKER_PASS: DOCKER_PASS
  DOCKER_IMAGE_URL: "$DOCKER_USER/$DOCKER_APP"
  DOCKER_IMAGE_FULL_URL: "$DOCKER_IMAGE_URL:$TRAVIS_COMMIT"
  HEROKU_API_KEY: HEROKU_API_KEY
  HEROKU_DOCKER_REGISTRY: "registry.heroku.com"

stages:
  - build
  - test
  - deploy

jobs:
  include:
    - stage: build
      script:
          - docker login -u $DOCKER_USER -p $DOCKER_PASS
          - docker build -t $DOCKER_IMAGE_FULL_URL .
          - docker push $DOCKER_IMAGE_FULL_URL

    - stage: test
      script:
          - docker run $DOCKER_IMAGE_FULL_URL composer run-script run-unit-tests

    - stage: deploy
      script:
          - docker login --username=_ --password=$HEROKU_API_KEY $HEROKU_DOCKER_REGISTRY
          - docker pull $DOCKER_IMAGE_FULL_URL
          - docker tag $DOCKER_IMAGE_FULL_URL $HEROKU_DOCKER_IMAGE_URL/$DOCKER_APP/web:$TRAVIS_COMMIT
          - docker push $HEROKU_DOCKER_IMAGE_URL/$DOCKER_APP/web:$TRAVIS_COMMIT