variables:
  DOCKER_APP: DOCKER_APP
  DOCKER_USER: DOCKER_USER
  DOCKER_PASS: DOCKER_PASS
  HEROKU_API_KEY: HEROKU_API_KEY
  HEROKU_DOCKER_REGISTRY: "registry.heroku.com"

stages:
  - build
  - test
  - deploy

jobs:
  include:
    - stage: build
      script:
          - docker login -u $DOCKER_USER -p $DOCKER_PASS
          - docker build -t $DOCKER_USER/$DOCKER_APP .
          - docker push $DOCKER_USER/$DOCKER_APP

    - stage: test
      script:
          - docker run $DOCKER_USER/$DOCKER_APP composer run run-unit-tests

    - stage: deploy
      script:
          - docker login --username=_ --password=$HEROKU_API_KEY $HEROKU_DOCKER_REGISTRY
          - docker pull $DOCKER_USER/$DOCKER_APP
          - docker tag $DOCKER_USER/$DOCKER_APP $HEROKU_DOCKER_IMAGE_URL/$DOCKER_APP
          - docker push $HEROKU_DOCKER_IMAGE_URL/$DOCKER_APP/web