version: '2'

services:
    web:
        build:
           context: .
           dockerfile: Dockerfile
           args:
               BUILD_ENV: dev
        container_name: booth-web
        ports:
            - "8080:8000"
        volumes:
            - .:/home/docker/www
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
        env_file:
            - .env
        networks:
            - code-network
    mariadb:
        image: mariadb
        container_name: booth-db
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: booth
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
