version: '2'
services:
    web:
        build:
           context: .
           dockerfile: Dockerfile
        container_name: booth-web
        ports:
            - '8001:80'
        volumes:
            - .:/home/docker/www
            #- ./docker/site.conf:/opt/docker/etc/nginx/vhost.conf
        env_file: .env
        networks:
            - code-network
    mariadb:
        image: mariadb
        container_name: booth-db
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: booth
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
